version: "3.8'

services:
  app:
    image: python:3.10
    container_name: python-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus: latest
    container_name: prometheus
    volumes:
      -. /prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "8070:8070"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana: latest
    container_name: grafana
    ports:
      - "5000:5000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net
    depends_on:
      - prometheus

volumes:
  grafana-storage:

networks:
  monitor-net: