name: Deploy App to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to fresh EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_IP_PG }}
          username: ${{ secrets.EC2_USER_PG }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. Instalar Docker si no está
            if ! command -v docker &> /dev/null
            then
              echo "Instalando Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # 2. Instalar Docker Compose si no está
            if ! command -v docker-compose &> /dev/null
            then
              echo "Instalando Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
                -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # 3. Clonar el repositorio si no existe
            if [ ! -d "Prom_Grafa" ]; then
              git clone https://github.com/jhosa20/Prom_Grafa.git
            fi

            # 4. Ingresar, actualizar y desplegar solo la app
            cd Prom_Grafa
            git pull origin main
            docker-compose up -d app  