deploy-to-ec2:
  needs: build-and-push
  runs-on: ubuntu-latest
steps:
  - name: SSH into EC2 and deploy container
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_IP_PG }}
    username: ${{ secrets.EC2_USER_PG }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      echo "${{ secrets.GH_TOKEN_PG }}" | docker login ghcr.io -u ${{ secrets.GH_USERNAME_GIT }} --password-stdin
        docker pull ghcr.io/${{ secrets.GH_USERNAME_GIT }}/fastapi-app:latest
        docker stop fastapi-app || true
        docker rm fastapi-app || true
        docker run -d -p 8000:8000 --name fastapi-app ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-app:latest